name: "BUILD"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          platform: linux/amd64
        - arch: arm32v7
          platform: linux/arm/v7
          
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Cross Toolchain
      run: |
        sudo apt update
        sudo apt install -y libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev build-essential bison flex libssl-dev bc gcc-11-arm-linux-gnueabihf
        echo "########################"
        ls -a
        echo "########################"
        whereis gcc-arm-linux-gnueabi
        echo "########################"
        whereis gcc-arm-linux-gnueabihf
        echo "########################"
        whereis arm-linux-gnueabi-gcc
        echo "########################"
        whereis arm-linux-gnueabihf-gcc
        gcc-arm-linux-gnueabihf --version
    - name: Initialize libseccomp
      uses: ./.github/actions/setup
    - name: configure
      run: ./configure --build=x86_64 --host=arm --prefix=${GITHUB_WORKSPACE}/${{ matrix.arch }}/out
    - name: make
      run: make
    - name: make install
      run: make install
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: libseccomp
        path: ${{ github.workspace }}/${{ matrix.arch }}/out
        retention-days: 7 
