name: "BUILD"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
          
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: configure
      run: ./configure --build=x86_64-unknown-linux --host=arm-linux-gnueabihf
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        retention-days: 7 
