name: "BUILD"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          platform: linux/amd64
        - arch: arm32v7
          platform: linux/arm/v7
          
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize libseccomp
      uses: ./.github/actions/setup

    - name: Install Cross Toolchain
      run: |
        sudo apt update
        sudo apt install -y libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev build-essential bison flex libssl-dev bc gcc-arm-linux-gnueabihf
    
    - name: configure
      run: |
        export CC=arm-linux-gnueabihf-gcc
        ./configure --build=x86_64-unknown-linux --host=arm-linux-gnueabihf --prefix=${GITHUB_WORKSPACE}/${{ matrix.arch }}/out
    
    - name: make
      run: make
    
    - name: make install
      run: make install
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: libseccomp
        path: ${{ github.workspace }}/${{ matrix.arch }}/out
        retention-days: 7 
